### ISSUE TITLE
If the BE is informed of a player leaving, it will remove the player from the games playerlist

### ISSUE THREAD

**Issue by Dedphish** [sopra-fs24-group-23/sopra24_server#143]
This includes:
- creating a leave **_game_** (as opposed to lobby) message mapping
- creating a service function
- (perhaps creating a function in Game.java)

**Comment by nilshgt** [comment]
https://github.com/sopra-fs24-group-23/sopra24_server/commit/57bab7e37b152e875500edc84a4dd11af209a0cd
